In [1]:
import operator

with open("20221211-AOC-Day11-Input.txt", "r") as f:
    inst = f.read().strip().split('\n\n')

def get_operators(x:str):
    val_x, op, val_y = x.split()
    if val_x.isnumeric():
        val_x = int(val_x)
    if val_y.isnumeric():
        val_y = int(val_y)
    return val_x, op, val_y

def create_dict(inst):
    monkey_dict={}
    for monkey in inst:
        parts = monkey.split('\n')
        monkey_dict[parts[0].split(':')[0]]={
                            'items':parts[1].split(':')[1].strip().split(', '),
                            'operation':parts[2].split('= ')[1].strip(),
                            'test':int(parts[3].split('by ')[1]),
                            'if true':parts[4].split('to ')[1].capitalize(),
                            'if false':parts[5].split('to ')[1].capitalize(),
                            'inspection':0
                            }
    return monkey_dict

ops = { "+": operator.add, "-": operator.sub, "*": operator.mul, "/": operator.truediv }

monkey_dict = create_dict(inst)

for r in range(20):
    for k,v in monkey_dict.items():
        if len(monkey_dict[k]['items'])>0:
            items = [int(x) for x in reversed(monkey_dict[k]['items'])]
            monkey_dict[k]['items']=[]
            monkey_dict[k]['inspection'] += len(items)
            for item in items:
                val_x, op, val_y = get_operators(monkey_dict[k]['operation'])
                if val_x == 'old':
                    val_x = int(item)
                if val_y == 'old':
                    val_y = int(item)
                new = ops[op](val_x,val_y)
                new = round(new/3)
                if new%int(monkey_dict[k]['test']) == 0:
                    move_to = monkey_dict[k]['if true']
                    monkey_dict[move_to]['items'].append(new)
                else:
                    move_to = monkey_dict[k]['if false']
                    monkey_dict[move_to]['items'].append(new)
            continue

inspections = []
for k,v in monkey_dict.items():
    print(f"{k} conducted {monkey_dict[k]['inspection']} inspections")
    inspections.append(monkey_dict[k]['inspection'])

a,b = sorted(inspections)[-2:]
print(a,b)
print(a*b)

Monkey 0 conducted 68 inspections
Monkey 1 conducted 245 inspections
Monkey 2 conducted 202 inspections
Monkey 3 conducted 188 inspections
Monkey 4 conducted 251 inspections
Monkey 5 conducted 190 inspections
Monkey 6 conducted 54 inspections
Monkey 7 conducted 68 inspections
245 251


61495

In [2]:
monkeys = [0, 1, 2, 3, 4, 5, 6, 7]

monkey_0_inspections = 0
monkey_1_inspections = 0
monkey_2_inspections = 0
monkey_3_inspections = 0
monkey_4_inspections = 0
monkey_5_inspections = 0
monkey_6_inspections = 0
monkey_7_inspections = 0

for round in range(20):
  # Monkey 0
  for item in [65, 58, 93, 57, 66]:
    new = item * 7
    if new % 19 == 0:
      monkey_6_inspections += 1
    else:
      monkey_4_inspections += 1

  # Monkey 1
  for item in [76, 97, 58, 72, 57, 92, 82]:
    new = item + 4
    if new % 3 == 0:
      monkey_7_inspections += 1
    else:
      monkey_5_inspections += 1

  # Monkey 2
  for item in [90, 89, 96]:
    new = item * 5
    if new % 13 == 0:
      monkey_5_inspections += 1
    else:
      monkey_1_inspections += 1

  # Monkey 3
  for item in [72, 63, 72, 99]:
    new = item * item
    if new % 17 == 0:
      monkey_0_inspections += 1
    else:
      monkey_4_inspections += 1

  # Monkey 4
  for item in [65]:
    new = item + 1
    if new % 2 == 0:
      monkey_6_inspections += 1
    else:
      monkey_2_inspections += 1

  # Monkey 5
  for item in [97, 71]:
    new = item + 8
    if new % 11 == 0:
      monkey_7_inspections += 1
    else:
      monkey_3_inspections += 1

  # Monkey 6
  for item in [83, 68, 88, 55, 87, 67]:
    new = item + 2
    if new % 5 == 0:
      monkey_2_inspections += 1
    else:
      monkey_1_inspections += 1

  # Monkey 7
  for item in [64, 81, 50, 96, 82, 53, 62, 92]:
    new = item + 5
    if new % 7 == 0:
      monkey_3_inspections += 1
    else:
      monkey_0_inspections += 1

In [3]:
inspections = [monkey_0_inspections, monkey_1_inspections, monkey_2_inspections, monkey_3_inspections, monkey_4_inspections, monkey_5_inspections, monkey_6_inspections, monkey_7_inspections]


In [4]:
inspections

[160, 120, 60, 40, 160, 120, 40, 20]

In [1]:
import numpy as np

In [4]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [7]:
print(a<=3)

[ True  True  True  True False]


In [9]:
import pandas as pd

In [12]:
import pandas as pd
import numpy as np

s = pd.Series([np.nan, 1, 2, np.nan, 3])
s = s.fillna(method='ffill')

print(s)

0    NaN
1    1.0
2    2.0
3    2.0
4    3.0
dtype: float64


In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20

In [62]:
a = np.array([2,6,2,8,4,0,1,5,7]).reshape(3,3)
print(a)

[[2 6 2]
 [8 4 0]
 [1 5 7]]


In [30]:
output_dict = {
  'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
  'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
  'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
  'max': [[6, 7, 8], [2, 5, 8], 8],
  'min': [[0, 1, 2], [0, 3, 6], 0],
  'sum': [[9, 12, 15], [3, 12, 21], 36]
}


In [54]:
a.sum(axis=1)

array([ 9, 14, 16])

In [63]:

output_dict['mean'] = [list(a.mean(axis=0)),list(a.mean(axis=1)), a.mean()]
output_dict['variance'] = [list(a.var(axis=0)),list(a.var(axis=1)), a.var()]
output_dict['standard deviation'] = [list(a.std(axis=0)),list(a.std(axis=1)), a.std()]
output_dict['max'] = [list(a.max(axis=0)),list(a.max(axis=1)), a.max()]
output_dict['min'] = [list(a.min(axis=0)),list(a.min(axis=1)), a.min()]
output_dict['sum'] = [list(a.sum(axis=0)),list(a.sum(axis=1)), a.sum()]



In [64]:
output_dict

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}

In [72]:
import numpy as np

def calculate(x:list):
  if len(x) < 9:
        raise ValueError('List must contain nine numbers.')
  a = np.array(x).reshape(3,3)
  calculations = {}
  
  calculations['mean'] = [list(a.mean(axis=0)),list(a.mean(axis=1)), a.mean()]
  calculations['variance'] = [list(a.var(axis=0)),list(a.var(axis=1)), a.var()]
  calculations['standard deviation'] = [list(a.std(axis=0)),list(a.std(axis=1)), a.std()]
  calculations['max'] = [list(a.max(axis=0)),list(a.max(axis=1)), a.max()]
  calculations['min'] = [list(a.min(axis=0)),list(a.min(axis=1)), a.min()]
  calculations['sum'] = [list(a.sum(axis=0)),list(a.sum(axis=1)), a.sum()]

  return calculations

In [75]:
df = pd.read_csv('adult.data.csv')

In [81]:
race_count = df.race.value_counts()

In [95]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

In [127]:
(df['education'].value_counts(normalize=True)*100)[['Bachelors','Masters','Doctorate']]

Bachelors    16.446055
Masters       5.291607
Doctorate     1.268389
Name: education, dtype: float64

In [149]:
(df[~df['education'].isin(['Bachelors','Masters','Doctorate'])]['salary'].value_counts(normalize=True)*100)['>50K']

17.3713601914639

In [205]:
df[(df['native-country']=='India') & (df['salary']=='>50K')]['occupation'].value_counts().index[0]

'Prof-specialty'

In [206]:
import pandas as pd


def calculate_demographic_data(print_data=True):
    # Read data from file
    df = pd.read_csv('adult.data.csv')

    # How many of each race are represented in this dataset? This should be a Pandas series with race names as the index labels.
    race_count = df.race.value_counts()

    # What is the average age of men?
    average_age_men = df[df['sex']=='Male']['age'].mean()

    # What is the percentage of people who have a Bachelor's degree?
    percentage_bachelors = (df['education'].value_counts(normalize=True)*100)['Bachelors']

    # What percentage of people with advanced education (`Bachelors`, `Masters`, or `Doctorate`) make more than 50K?
    # What percentage of people without advanced education make more than 50K?

    # with and without `Bachelors`, `Masters`, or `Doctorate`
    higher_education = (df['education'].value_counts(normalize=True)*100)[['Bachelors','Masters','Doctorate']].sum()    
    lower_education = 100-(df['education'].value_counts(normalize=True)*100)[['Bachelors','Masters','Doctorate']].sum()

    # percentage with salary >50K
    higher_education_rich = (df[df['education'].isin(['Bachelors','Masters','Doctorate'])]['salary'].value_counts(normalize=True)*100)['>50K']
    lower_education_rich = (df[~df['education'].isin(['Bachelors','Masters','Doctorate'])]['salary'].value_counts(normalize=True)*100)['>50K']

    # What is the minimum number of hours a person works per week (hours-per-week feature)?
    min_work_hours = df['hours-per-week'].min()

    # What percentage of the people who work the minimum number of hours per week have a salary of >50K?
    num_min_workers = df[df['hours-per-week']==df['hours-per-week'].min()]['hours-per-week'].count()

    rich_percentage = (df[df['hours-per-week']==df['hours-per-week'].min()]['salary'].value_counts(normalize=True)*100)['>50K']

    # What country has the highest percentage of people that earn >50K?
    highest_earning_country = df[df['salary']=='>50K']['native-country'].value_counts().index[0]
    highest_earning_country_percentage = (df[df['salary']=='>50K']['native-country'].value_counts(normalize=True)*100)[0]

    # Identify the most popular occupation for those who earn >50K in India.
    top_IN_occupation = df[(df['native-country']=='India') & (df['salary']=='>50K')]['occupation'].value_counts().index[0]

    # DO NOT MODIFY BELOW THIS LINE

    if print_data:
        print("Number of each race:\n", race_count) 
        print("Average age of men:", average_age_men)
        print(f"Percentage with Bachelors degrees: {percentage_bachelors}%")
        print(f"Percentage with higher education that earn >50K: {higher_education_rich}%")
        print(f"Percentage without higher education that earn >50K: {lower_education_rich}%")
        print(f"Min work time: {min_work_hours} hours/week")
        print(f"Percentage of rich among those who work fewest hours: {rich_percentage}%")
        print("Country with highest percentage of rich:", highest_earning_country)
        print(f"Highest percentage of rich people in country: {highest_earning_country_percentage}%")
        print("Top occupations in India:", top_IN_occupation)

    return {
        'race_count': race_count,
        'average_age_men': average_age_men,
        'percentage_bachelors': percentage_bachelors,
        'higher_education_rich': higher_education_rich,
        'lower_education_rich': lower_education_rich,
        'min_work_hours': min_work_hours,
        'rich_percentage': rich_percentage,
        'highest_earning_country': highest_earning_country,
        'highest_earning_country_percentage':
        highest_earning_country_percentage,
        'top_IN_occupation': top_IN_occupation
    }


In [207]:
calculate_demographic_data()

Number of each race:
 White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: race, dtype: int64
Average age of men: 39.43354749885268
Percentage with Bachelors degrees: 16.44605509658794%
Percentage with higher education that earn >50K: 46.535843011613935%
Percentage without higher education that earn >50K: 17.3713601914639%
Min work time: 1 hours/week
Percentage of rich among those who work fewest hours: 10.0%
Country with highest percentage of rich: United-States
Highest percentage of rich people in country: 91.45517153424308%
Top occupations in India: Prof-specialty


{'race_count': White                 27816
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
 Name: race, dtype: int64,
 'average_age_men': 39.43354749885268,
 'percentage_bachelors': 16.44605509658794,
 'higher_education_rich': 46.535843011613935,
 'lower_education_rich': 17.3713601914639,
 'min_work_hours': 1,
 'rich_percentage': 10.0,
 'highest_earning_country': 'United-States',
 'highest_earning_country_percentage': 91.45517153424308,
 'top_IN_occupation': 'Prof-specialty'}